name: flutter_coin_zone
description: "A new Flutter project."

flutter_icons:
  android: "luancher_logo"
  image_path: "assets/images/logo.png"
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android: true 
  
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2
  
dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.1.1
  intl: ^0.20.2
  get: ^4.7.2
  url_launcher: ^6.3.1
  dio: ^5.8.0+1
  fl_chart: ^0.70.2
  image_picker: ^1.1.2
  loading_animation_widget: ^1.3.0
  screenshot: ^3.0.0
  path_provider: ^2.1.5
  flutter_staggered_grid_view: ^0.7.0
  image_gallery_saver: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/tabbar/
    - assets/images/avator/
    - assets/images/home/
    - assets/images/profile/
    - assets/images/lottery/
    - assets/images/create/
    - assets/images/stickers/
    - assets/images/NFTs/
    - assets/images/splash.png

  fonts:
    - family: Outfit
      fonts: 
        - asset: assets/fonts/Outfit/Outfit-VariableFont_wght.ttf
        - asset: assets/fonts/Outfit/static/Outfit-Black.ttf
        - asset: assets/fonts/Outfit/static/Outfit-Bold.ttf
        - asset: assets/fonts/Outfit/static/Outfit-ExtraBold.ttf
        - asset: assets/fonts/Outfit/static/Outfit-ExtraLight.ttf
        - asset: assets/fonts/Outfit/static/Outfit-Light.ttf
        - asset: assets/fonts/Outfit/static/Outfit-Medium.ttf
        - asset: assets/fonts/Outfit/static/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit/static/Outfit-SemiBold.ttf
        - asset: assets/fonts/Outfit/static/Outfit-Thin.ttf
          style: italic